force-app/main/default/objects/Book_Copy__c/Book_Copy__c.object-meta.xml
<CustomObject>
    <description>Book copies available in the library for borrowing</description>
    <label>Book Copy</label>
    <nameField>
        <displayFormat>BC-{000000}</displayFormat>
        <label>Book Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Copies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Book_Copy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the book copy</description>
    <inlineHelpText>Current status of the book copy</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Borrowed</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing__c/Borrowing__c.object-meta.xml
<CustomObject>
    <description>Represents a book borrowing transaction</description>
    <label>Borrowing</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Borrowing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Borrowings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Borrowing__c/fields/Book_Copy__c.field-meta.xml
<CustomField>
    <fullName>Book_Copy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Copy of the book</description>
    <inlineHelpText>Copy of the book</inlineHelpText>
    <label>Book Copy</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Book_Copy__c.Book__c</field>
            <operation>equals</operation>
            <valueField>$Source.Book__c</valueField>
        </filterItems>
        <filterItems>
            <field>Book_Copy__c.Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Book_Copy__c</referenceTo>
    <relationshipLabel>Borrowings</relationshipLabel>
    <relationshipName>Borrowings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Borrowing__c/fields/Devolution_Status__c.field-meta.xml
<CustomField>
    <fullName>Devolution_Status__c</fullName>
    <description>Book devolution status</description>
    <inlineHelpText>Book devolution status</inlineHelpText>
    <label>Devolution Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Borrowing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the borrowing</description>
    <inlineHelpText>Current status of the borrowing</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BorrowingHelper.cls
public class BorrowingHelper {
    public static void updateBookCopyStatus(List<Borrowing__c> borrowings) {
        List<Book_Copy__c> bookCopiesToUpdate = new List<Book_Copy__c>();

        for(Borrowing__c borrowing : borrowings) {
            Book_Copy__c bookCopy = new Book_Copy__c();
            bookCopy.Id = borrowing.Book_Copy__c;

            switch on borrowing.Status__c {
                when 'Scheduled' {
                    bookCopy.Status__c = 'Reserved';
                }
                when 'In progress' {
                    bookCopy.Status__c = 'Borrowed';
                }
                when 'Closed' {
                    if(borrowing.Devolution_Status__c == 'Returned') {
                        bookCopy.Status__c = 'Available';
                    } else if(borrowing.Devolution_Status__c == 'Damaged') {
                        bookCopy.Status__c = 'Damaged';
                    } else if(borrowing.Devolution_Status__c == 'Missed') {
                        bookCopy.Status__c = 'Missing';
                    }
                }
            }

            bookCopiesToUpdate.add(bookCopy);
        }

        update bookCopiesToUpdate;
    }
}